#Outdated was not used in the final analysis

#This function uses the full.sim.gen function to generate a fake schedule and fake results according
# to the parameters you provide it. It has a lot of arguements and is probably the most complicated
# function that exists for this LARC research, however most of its arguements are identical to those
# in the full.sim.gen function because they are needed to be fed into the full.sim.gen functions
# that exist within this one; as such I wont explain those as they are elaborated on in the file for
# full.sim.gen. The arguements unique to this function are the following.
#drawtype- this indicates what type of function should be used to generate the unique strengths for 
#       each simulation. It should be a function without arguements such as "rgamma" or "rpois" 
#       without the parentheses () following the function. If you want the strengths to remain
#       constant for each simulation leave this arguement at its default value of NULL with the 
#       quotations and no capital letters.
#simulations- use this arguement to tell the function how many iterations of the simulation to run.
#arg1, arg2, arg3- these are the arguements to be fed into your drawtype function if it exists. If
#       there is no drawtype function then these should be kept as NULL and if you need less than 
#       three (which will typically be the case) start with arg1 and leave unused ones blank, also
#       be sure to enter them in in the order the the drawtype would require them (ignore the n
#       arguement for any funtion).
#The results that this function are extensive and can be split into three groups: General, 
# Bradley-Terry, and Thurstone-Mosteller. By group: 
#General:
#SimulatedData-returns the average results of strengths and wins for all the simulations.
#FullSimulationComparison-returns a table with a count of how many times each model preformed the
#       best over all the simulations.
#Comparison-returns the total number of times each model preformed better for each game within each
#       simulation the function run. Tie will at least equal the number of simulations because the
#       first week of each simulation will result in a tie.
#Proportion-gives the percentages based on the comparison values.
#Bradley-Terry:
#BradleyTerryStrengths-returns a matrix of all of the final strenghs generated by each simulation
#BradleyTerryVariance-returns the variances of all strengths assigned to each team over the course
#       of the entirity of the simulation.
#BradleyTerryBias-returns the bias of all strengths assigned to each team over the simulation.
#BradleyTerryPercentPerfect-provides what percent of the final ranking that matched with the correct
#       order.
#Thurstone-Mosteller: Contains the same results that exist for Bradley-Terry but for Thurstone-Mosteller

progresspredict.simulation <- function(teams, weeks=NULL, strengths=NULL, drawtype=NULL, divisions,
                                       gid, god=NULL, god.type="times", enddate=Sys.Date(), type="BT",
                                       simulations=1000, arg1=NULL, arg2=NULL, arg3=NULL) {
  #The beginning section sets up the teams and default strengths of the teams for the simulation the
  # same way they are set up in full.sim.gen
  if (length(teams) > 1) {
    N <- length(teams)
  } else {
    N <- teams
  }
  strengthsTM <- rep(0, N)
  strengthsBT <- rep(0, N)
  wins <- rep(0, N)
  strongTM <- matrix(0, N, simulations)
  strongBT <- matrix(0, N, simulations)
  varsTM <- rep(0, N)
  varsBT <- rep(0, N)
  prcntTM <- vector()
  prcntBT <- vector()
  if (length(teams) > 1 && length(strengths) > 1) {
    swtch <- TRUE
  } else {
    swtch <- FALSE
  }
  if (length(teams) > 1) {
    Team <- teams
    teamsC <- length(teams)
    if (is.null(weeks)) {
      weeks <- teamsC
    }
  } else {
    if (is.null(weeks)) {
      weeks <- teams
    }
    teamsC <- teams
    pkmn <- sort(c("Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pichu", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "NidoranM","NidoranF", "Nidorina", "Nidoqueen", "Nidorino", "Nidoking", "Cleffa", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Igglybuff", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Crobat", "Oddish", "Gloom", "Vileplume", "Bellossom", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth",
                   "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Politoed", "Abra", "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Slowking", "Magnemite", "Magneton", "Magnezone", "Farfetchd", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Steelix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Kangaskhan", "Cubone",
                   "Marowak", "Tyrogue", "Hitmonlee", "Hitmonchan", "Hitmontop", "Lickitung", "Lickilicky", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Rhyperior", "Happiny", "Chansey", "Blissey", "Tangela", "Tangrowth", "Horsea", "Seadra", "Kingdra", "Goldeen", "Seaking", "Staryu", "Starmie", "MimeJr", "MrMime", "Scyther", "Scizor", "Smoochum", "Jynx", "Elekid", "Electabuzz", "Electivire", "Magby", "Magmar", "Magmortar", "Pinsir", "Tauros", "Miltank", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon", "Porygon", "Porygon2", "PorygonZ", "Omanyte", "Omastar", "Kabuto",
                   "Kabutops", "Aerodactyl", "Munchlax", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", "Chinchou", "Lanturn", "Togepi", "Togetic", "Togekiss", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Azurill", "Marill", "Azumarill", "Bonsly", "Sudowoodo", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Ambipom", "Sunkern", "Sunflora", "Yanma", "Yanmega", "Wooper", "Quagsire", "Murkrow", "Honchkrow",
                   "Misdreavus", "Mismagius", "Unown", "Wynaut", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar", "Gliscor", "Snubbull", "Granbull", "Qwilfish", "Shuckle", "Heracross", "Sneasel", "Weavile", "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Mamoswine", "Corsola", "Remoraid", "Octillery", "Delibird", "Mantyke", "Mantine", "Skarmory", "Houndour", "Houndoom", "Phanpy", "Donphan", "Stantler", "Smeargle", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "HoOh", "Celebi", "Treecko", "Grovyle", "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert",
                   "Poochyena", "Mightyena", "Zigzagoon", "Linoone", "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry", "Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Gallade", "Surskit", "Masquerain", "Shroomish", "Breloom", "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask", "Shedinja", "Whismur", "Loudred", "Exploud", "Makuhita", "Hariyama", "Nosepass", "Probopass", "Skitty", "Delcatty", "Sableye", "Mawile", "Aron", "Lairon", "Aggron", "Meditite", "Medicham", "Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", "Budew", "Roselia",
                   "Roserade", "Gulpin", "Swalot", "Carvanha", "Sharpedo", "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal", "Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon", "Cacnea", "Cacturne", "Swablu", "Altaria", "Zangoose", "Seviper", "Lunatone", "Solrock", "Barboach", "Whiscash", "Corphish", "Crawdaunt", "Baltoy", "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas", "Milotic", "Castform", "Kecleon", "Shuppet", "Banette", "Duskull", "Dusclops", "Dusknoir", "Tropius", "Chingling", "Chimecho", "Absol", "Snorunt", "Glalie", "Froslass", "Spheal", "Sealeo", "Walrein", "Clamperl", "Huntail", "Gorebyss", "Relicanth", "Luvdisc",
                   "Bagon", "Shelgon", "Salamence", "Beldum", "Metang", "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre", "Groudon", "Rayquaza", "Jirachi", "Deoxys", "Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup", "Empoleon", "Starly", "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune", "Shinx", "Luxio", "Luxray", "Cranidos", "Rampardos", "Shieldon", "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "Vespiquen", "Pachirisu", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos", "Gastrodon", "Drifloon", "Drifblim", "Buneary", "Lopunny", "Glameow", "Purugly",
                   "Stunky", "Skuntank", "Bronzor", "Bronzong", "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp", "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", "Croagunk", "Toxicroak", "Carnivine", "Finneon", "Lumineon", "Snover", "Abomasnow", "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran", "Regigigas", "Giratina", "Cresselia", "Phione", "Manaphy", "Darkrai", "Shaymin", "Arceus", "Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", "Oshawott", "Dewott", "Samurott", "Patrat", "Watchog", "Lillipup", "Herdier", "Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage", "Pansear", "Simisear",
                   "Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", "Blitzle", "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", "Drilbur", "Excadrill", "Audino", "Timburr", "Gurdurr", "Conkeldurr", "Tympole", "Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny", "Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", "Basculin", "Sandile", "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", "Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph", "Yamask", "Cofagrigus", "Tirtouga", "Carracosta", "Archen", "Archeops", "Trubbish",
                   "Garbodor", "Zorua", "Zoroark", "Minccino", "Cinccino", "Gothita", "Gothorita", "Gothitelle", "Solosis", "Duosion", "Reuniclus", "Ducklett", "Swanna", "Vanillite", "Vanillish", "Vanilluxe", "Deerling", "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss", "Frillish", "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", "Klink", "Klang", "Klinklang", "Tynamo", "Eelektrik", "Eelektross", "Elgyem", "Beheeyem", "Litwick", "Lampent", "Chandelure", "Axew", "Fraxure", "Haxorus", "Cubchoo", "Beartic", "Cryogonal", "Shelmet", "Accelgor", "Stunfisk", "Mienfoo", "Mienshao", "Druddigon", "Golett", "Golurk",
                   "Pawniard", "Bisharp", "Bouffalant", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", "Durant", "Deino", "Zweilous", "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", "Virizion", "Tornadus", "Thundurus", "Reshiram", "Zekrom", "Landorus", "Kyurem", "Keldeo", "Meloetta", "Genesect", "Chespin", "Quilladin", "Chesnaught", "Fennekin", "Braixen", "Delphox", "Froakie", "Frogadier", "Greninja", "Bunnelby", "Diggersby", "Fletchling", "Fletchinder", "Talonflame", "Scatterbug",
                   "Spewpa", "Vivillon", "Litleo", "Pyroar", "Flab?b?", "Floette", "Florges", "Skiddo", "Gogoat", "Pancham", "Pangoro", "Furfrou", "Espurr", "Meowstic", "Honedge", "Doublade", "Aegislash", "Spritzee", "Aromatisse", "Swirlix", "Slurpuff", "Inkay", "Malamar", "Binacle", "Barbaracle", "Skrelp", "Dragalge", "Clauncher", "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt", "Tyrantrum", "Amaura", "Aurorus", "Hawlucha", "Dedenne", "Carbink", "Goomy", "Sliggoo", "Goodra", "Klefki", "Phantump", "Trevenant", "Pumpkaboo", "Gourgeist", "Bergmite", "Avalugg", "Noibat", "Noivern", "Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa", "Volcanion", "Magearna"))
    Team <- c(LETTERS[1:min(teams,26)],
              letters[ifelse(teams>26,1,0):ifelse(teams>26,min(teams-26,26),0)],
              month.abb[ifelse(teams>52,1,0):ifelse(teams>52,min(teams-52,12),0)],
              month.name[ifelse(teams>64,1,0):ifelse(teams>64,min(teams-64,12),0)],
              pkmn[ifelse(teams>76,1,0):ifelse(teams>76,min(teams-76,722),0)])
  }
  #This is the first deviation from full.sim.gen in that it makes the default strengths match the
  # drawtype specified if the strengths are not provided.
  if (is.null(strengths)) {
    if (is.null(drawtype)) {
      Strength <- seq(2,.001,length.out=teamsC)
    } else {
      if (is.null(arg1)) {
        Strength <- (abs(drawtype(teamsC))+.001)
      } else {
        if (is.null(arg2)) {
          Strength <- (abs(drawtype(teamsC,arg1))+.001)
        } else {
          if (is.null(arg3)) {
            Strength <- (abs(drawtype(teamsC,arg1,arg2))+.001)
          } else {
            Strength <- (abs(drawtype(teamsC,arg1,arg2,arg3))+.001)
          }
        }
      }
    }
  } else {
    Strength <- strengths
  }
  if (swtch == FALSE) {
    Strength <- rev(sort(Strength))
  }
  #This locks in the strengths so they can be compared in thier rank for PercentPerfect
  strengths <- Strength
  #These are set up variables to be filled and adjusted throughout the simulation
  cmprsn <- table(c("Bradley-Terry","Thurstone-Mosteller","Tie"))-1
  fllcmp <- table(c("Bradley-Terry","Thurstone-Mosteller","Tie"))-1
  
  TST <- data.frame(Team,Strength)
  #Here is the loop for the simulation study
  for (i in 1:simulations) {
   #It begins by generating a completed season of sports to add to the analyses for each simulation
    if (is.null(drawtype)) {
      df <- full.sim.gen(teams, weeks, strengths, divisions, gid, god, god.type, enddate, type)
    } else {
      if (is.null(arg1)) {
        df <- full.sim.gen(teams, weeks, (abs(drawtype(teamsC))+.001), divisions, gid, god,
                           god.type, enddate, type)
      } else {
        if (is.null(arg2)) {
          df <- full.sim.gen(teams, weeks, (abs(drawtype(teamsC,arg1))+.001), divisions, gid, 
                             god, god.type, enddate, type)
        } else {
          if (is.null(arg3)) {
            df <- full.sim.gen(teams, weeks, (abs(drawtype(teamsC,arg1,arg2))+.001), divisions, gid, 
                               god, god.type, enddate, type)
          } else {
            df <- full.sim.gen(teams, weeks, (abs(drawtype(teamsC,arg1,arg2,arg3))+.001), divisions,
                               gid, god, god.type, enddate, type)
          }
        }
      }
    }
    #This compiles a dataframe of the data created to be used for later comparisons
    round <- dataconfigure(df)
    #ProgressPredict is run for this round of the simulation
    pp <- progresspredict(df)
    #The number of times both Thurstone-Mosteller and Bradley-Terry are better is recorded
    cmprsn <- cmprsn + pp$Comparison
    if(pp$Comparison[1]==pp$Comparison[2]){
      fllcmp <- fllcmp + c(0,0,1)
    } else {
      fllcmp <- fllcmp + ifelse(pp$Comparison==max(pp$Comparison),1,0)
    }
    #These lines create the plot of the data that is created as the function runs.
    pt <- pp$ProgressionTable
    if (i == 1) {
      plot(pt$Week,pt$ThurstoneMosteller,col=2,ylim=c(0,teams))
    } else {
      points(pt$Week,pt$ThurstoneMosteller,pch=i,col=2)
    }
    points(pt$Week,pt$BradleyTerry,pch=i,col=4,cex=.75)
    #This creates a sample df to rank the teams by their final ProgressPredict generated strengths
    samdf <- data.frame(Team=round$Team,WT=round$WinsTotal,MS=pp$FinalTMStrenghs,BTS=pp$FinalBTStrenghs)
    #The remainder of the for loop compiles the results uniquie to both models analyzed in the
    # simulation as do the eight lines directly following the loop
    prpTM <- table(c(TST[order(-TST$Strength),]$Team,1,0)==c(samdf[order(-samdf$TMS),]$Team,0,1))
    prpTM <- prpTM-1
    prcntTM <- c(prcntTM,prop.table(prpTM)[2])
    prpBT <- table(c(TST[order(-TST$Strength),]$Team,1,0)==c(samdf[order(-samdf$BTS),]$Team,0,1))
    prpBT <- prpBT-1
    prcntBT <- c(prcntBT,prop.table(prpBT)[2])
    
    strongTM[,i] <- pp$FinalTMStrenghs
    strongBT[,i] <- pp$FinalBTStrenghs
    strengthsTM <- ((i - 1) * strengthsTM + pp$FinalTMStrenghs)/i
    strengthsBT <- ((i - 1) * strengthsBT + pp$FinalBTStrenghs)/i
    wins <- ((i - 1) * wins + round$WinsTotal)/i
  }
  varsTM <- vector()
  varsBT <- vector()
  for (i in 1:N) {
    varsTM[i] <- var(strongTM[i,])
    varsBT[i] <- var(strongBT[i,])
  }
  biTM <- strengthsTM/mean(strengthsTM) - TST$Strength/mean(TST$Strength)
  biBT <- strengthsBT/mean(strengthsBT) - TST$Strength/mean(TST$Strength)
  #This creates a summary df of the averages created by each loop of the simulation
  newdf <- data.frame(TST$Team, strengthsBT, strengthsTM, wins)
  names(newdf) <- c("Team","BradleyTerrySimulatedStrength","ThurstoneMostellerSimulatedStrength",
                    "WinsSummary")
  prcntgs <- prop.table(cmprsn)
  
  return(list(SimulatedData=newdf,BradleyTerryStrengths=strongBT,ThurstoneMostellerStrengths=strongM,
              BradleyTerryVariance=varsBT,ThurstoneMostellerVariance=varsM,BradleyTerryBias=biBT,
              ThurstoneMostellerBias=biM,BradleyTerryPercentPerfect=prcntBT,ThurstoneMostellerPercentPerfect=prcntM,
              FullSimulationComparison=fllcmp,Comparison=cmprsn,Proportion=prcntgs))
}

#The remaining code is timed example of this function with unset strengths gamma distributed and a
# Thurstune-Mosteller Base, it includes 5 simulations. Following the function and the timer lines
# are lines to read out the results of the simulation for both how the Bradley-Terry model and the 
# Thurstone-Mosteller model predicted things as well as presenting thier results.
go <- proc.time()
PPS.EX <- progresspredict.simulation(teams=16, weeks=NULL, strengths=NULL, drawtype=rgamma, 
                                     divisions=2, gid=2, god=NULL, god.type="times",
                                     enddate=Sys.Date(), type="TM", simulations=5, arg1=5, 
                                     arg2=2, arg3=NULL)
clock <- proc.time() - go
clock

PPS.EX$SimulatedData
PPS.EX$BradleyTerryStrengths
PPS.EX$ThurstoneMostellerStrengths
PPS.EX$BradleyTerryVariance
PPS.EX$ThurstoneMostellerVariance
PPS.EX$BradleyTerryBias
PPS.EX$ThurstoneMostellerBias
PPS.EX$BradleyTerryPercentPerfect
PPS.EX$ThurstoneMostellerPercentPerfect
PPS.EX$FullSimulationComparison
PPS.EX$Comparison
PPS.EX$Proportion
